version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: auth-db-user
      POSTGRES_PASSWORD: auth-db-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: workspace9801@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
